server:
  port: 9803

spring:
  application:
    name: SPRINGCLOUD-BUSI

eureka:
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true